platform :ios, ‘10.0’

use_frameworks!

target ’TestVideo’ do
    pod 'MBProgressHUD', '~> 1.0.0'
    pod ‘UICircularProgressRing’
    pod ‘ABVideoRangeSlider’
    pod ‘SnapKit’
    #pod ‘WillowTreeScrollingTabController’, :git => ‘https://github.com/willowtreeapps/WillowTreeScrollingTabController.git’, :tag => ‘0.1.1’
end

